/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'surface-tint': '#4a654f',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#473700',
        'on-surface': '#1b1c1a',
        'surface-variant': '#e4e2de',
        'on-secondary-container': '#78491d',
        'secondary-fixed-dim': '#fab983',
        'surface-dim': '#dbdad6',
        'tertiary': '#735c00',
        'on-surface-variant': '#424842',
        'inverse-surface': '#30312e',
        'on-background': '#1b1c1a',
        'secondary': '#845326',
        'on-error': '#ffffff',
        'surface-container-high': '#eae8e4',
        'surface-container': '#efeeea',
        'secondary-container': '#febc85',
        'tertiary-container': '#c39f27',
        'on-tertiary-fixed-variant': '#574500',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#2e1500',
        'inverse-primary': '#b0ceb4',
        'surface-bright': '#fbf9f5',
        'on-primary': '#ffffff',
        'surface-container-highest': '#e4e2de',
        'surface': '#fbf9f5',
        'tertiary-fixed-dim': '#e9c349',
        'error-container': '#ffdad6',
        'outline': '#737972',
        'on-primary-fixed-variant': '#334d38',
        'primary-fixed-dim': '#b0ceb4',
        'primary': '#4a654f',
        'primary-container': '#8daa91',
        'surface-container-low': '#f5f3ef',
        'primary-fixed': '#cceacf',
        'secondary-fixed': '#ffdcc2',
        'background': '#fbf9f5',
        'on-tertiary-fixed': '#241a00',
        'inverse-on-surface': '#f2f0ed',
        'on-secondary-fixed-variant': '#683c11',
        'outline-variant': '#c2c8c0',
        'on-primary-fixed': '#062010',
        'tertiary-fixed': '#ffe088',
        'on-secondary': '#ffffff',
        'on-primary-container': '#253f2b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'section-gap': '80px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        unit: '8px',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      padding: {
        'section-gap': '80px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
      },
    },
  },
  plugins: [],
}
